# 项目配置
name = "navigation-site"
main = "functions/[[path]].js"  # 保留此行，指定 Worker 入口点

# 页面配置
[site]
bucket = "./dist"
include = ["dist"]

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "navigation-db-local"
database_id = "43ff28e1-42d6-4e53-9657-0702ae1353b6"

[vars]
AUTH_ENABLED = "true"
AUTH_USERNAME = "admin"
AUTH_PASSWORD = "password"
AUTH_SECRET = "your-secret-key"